### ISSUE TITLE
image overflows on small devices

### ISSUE THREAD

**Issue by jnnkB** [okfde/jh-lauch-theme#119]
![Screen Shot 2021-06-09 at 14 58 55](https://user-images.githubusercontent.com/29376715/121358907-439fe700-c933-11eb-9fac-445cf798348c.png)

This could be fixed by something like

```css
main#content img {
    max-width: 100%;
    height: auto;
}
```

But I don't know wether this breaks anything else.
